server:
  port: 9082
spring:
  redis:
    host: 127.0.0.1
  datasource:
    url: jdbc:mysql://localhost/order_service_db
    username: root
    password: abcd1234
management:
  endpoints:
    web:
      base-path: /orders/actuator
dmall:
  inventory:
    url: http://localhost:9081
  shipping:
    url: http://localhost:9085
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://dmall-order-db.cti1pnc10c3g.rds.cn-north-1.amazonaws.com.cn/order_service_db
    username: admin
dmall:
  inventory:
    url: http://inventory-service:9080
  shipping:
    url: http://shipping-service:9080